name: Tweak Derleyici
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Bağımlılıkları Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libssl-dev

      - name: Theos ve SDK Kur
        uses: theos/setup-theos@v1
        with:
          archs: arm64 arm64e

      - name: Tweak'i Paketle
        run: |
          # Küçük harfli makefile'ı Theos'un tanıması için kopyalıyoruz
          if [ -f makefile ] && [ ! -f Makefile ]; then cp makefile Makefile; fi
          make package FINALPACKAGE=1 THEOS=/opt/theos
          
      - name: Hazır DEB Dosyasını Teslim Et
        uses: actions/upload-artifact@v4
        with:
          name: brazilix-tweak-paketi
          path: packages/*.deb
